#!/usr/bin/env bash

set -e
export PATH

usage() {
    cat <<HELP

genstrap - gentoo base system bootstrap
based on debootstrap

usage: genstrap

Options:
    -h              display this help page
    -d              choose directory
    -a              choose architecture
    -s              choose sub-architecture
    -e              extra download options
                    avalible:
                        hardened+nomultilib
                        hardened-selinux+nomultilib
                        hardened-selinux
                        hardened
                        nomultilib
                        systemd
                        uclibc-hardened
                        uclibc-vanilla
    -g              create repo config gentoo.conf
    -r              create /etc/resolv.conf
    -l              use a downloaded stage tarball
    -u              only download a tarball

Defaults:
    directory   =   current directory
    arch        =   amd64
    sub-arch    =   amd64
    extras      =   none
    gentoo.conf =   no

Avalible arches and sub-arches:
    alpha
                    alpha
    amd64
                    amd64
                    x32
    arm
                    armv4tl
                    armv5tel
                    armv6j
                    armv6j_hardfp
                    armv7a
                    armv7a_hardfp
    hppa
                    hppa32
                    hppa64
                    hppa1.1
                    hppa2.0
    ia64
                    ia64
    ppc
                    ppc
                    ppc64
                    ppc64le
    s390
                    s390
                    s390x
    sh
                    sh4
                    sh4a
    sparc
                    sparc64
    x86
                    x86
                    i486
                    i686

HELP
}

bold_msg() {
    echo "$(tput bold)$1$(tput sgr0)"
}

err_msg() {
    echo "$(tput bold)$1$(tput sgr0)"
    exit 1
}

lookup_stage() {
    TARBALL_LOCATION=$(wget -q -O - "https://gentoo.osuosl.org/releases/$ARCH/autobuilds/latest-stage3-$SUB$EXTRA.txt" | grep -E '^2' | grep -o '^\S*')
    # gives:
    # 20190821T214502Z/stage3-amd64-20190821T214502Z.tar.xz
    TARBALL_NAME=$(basename "$TARBALL_LOCATION")
    # gives:
    # stage3-amd64-20190821T214502Z.tar.xz
}

get_stage() {
    lookup_stage
    wget "https://gentoo.osuosl.org/releases/$ARCH/autobuilds/$TARBALL_LOCATION" -O $DIRECTORY/$TARBALL_NAME
}

unpack_stage() {
    tar xpf $DIRECTORY/stage3* -C $DIRECTORY
}

repo_conf() {
    mkdir -p $DIRECTORY/etc/portage/repos.conf
    cat > $DIRECTORY/etc/portage/repos.conf/gentoo.conf <<GENTOO_CONF
[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo
sync-type = rsync
sync-uri = rsync://rsync.gentoo.org/gentoo-portage
auto-sync = yes
sync-rsync-verify-jobs = 1
sync-rsync-verify-metamanifest = yes
sync-rsync-verify-max-age = 24
sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc
sync-openpgp-key-refresh-retry-count = 40
sync-openpgp-key-refresh-retry-overall-timeout = 1200
sync-openpgp-key-refresh-retry-delay-exp-base = 2
sync-openpgp-key-refresh-retry-delay-max = 60
sync-openpgp-key-refresh-retry-delay-mult = 4
GENTOO_CONF
}

resolv_conf() {
    cat > $DIRECTORY/etc/resolv.conf <<RESOLV_CONF
nameserver 1.1.1.1
nameserver 1.0.0.1
RESOLV_CONF
}

# Defaults

DIRECTORY="."

ARCH="amd64"
SUB="amd64"
EXTRA=""

DO_DOWNLOAD="yes"
DO_UNPACK="yes"

DO_GENTOO_CONF="no"
DO_RESOLV_CONF="no"

# Command line options

while [ -n "$1" ]; do
    case "$1" in
    -h | --help)
        usage
        exit 0
        ;;
    -d | --directory)
        DIRECTORY="$2"
        ;;
    -a | --arch)
        ARCH="$2"
        ;;
    -s | --sub_arch)
        SUB="$2"
        ;;
    -e | --extra)
        EXTRA="-$2"
        ;;
    -g | --repo_conf)
        DO_GENTOO_CONF="yes"
        ;;
    -r | --resolv_conf)
        DO_RESOLV_CONF="yes"
        ;;
    -l | --no-download)
        DO_DOWNLOAD="no"
        ;;
    -u | --no-unpack)
        DO_UNPACK="no"
        ;;
    -*)
        usage
        exit 1
        ;;
    esac
    shift
done

# Check root

(( $EUID == 0 )) || (
    err_msg "This script must be run with root privileges!"
)

# Do some work

if [ $DO_DOWNLOAD = "yes" ]; then
    bold_msg "Downloading for $SUB$EXTRA into $DIRECTORY ..."
    get_stage
    bold_msg "Stage downloaded, OK"
fi

if [ $DO_UNPACK = "yes" ]; then
    bold_msg "Unpacking stage tarball ..."
    unpack_stage
    bold_msg "Stage unpacked, OK"
fi

if [ $DO_GENTOO_CONF = "yes" ]; then
    bold_msg "Writing gentoo.conf ..."
    repo_conf
    bold_msg "Written $DIRECTORY/etc/portage/repos.conf/gentoo.conf , OK"
fi

if [ $DO_RESOLV_CONF = "yes" ]; then
    bold_msg "Writing resolv.conf ..."
    resolv_conf
    bold_msg "Written $DIRECTORY/etc/resolv.conf , OK"
fi