#!/usr/bin/env bash


set -e
export PATH


# Defaults

os_directory="."

os_arch="amd64"
os_subarch="amd64"
os_extra=""

do_download="yes"
do_unpack="yes"

do_gentoo_conf="no"
do_resolv_conf="no"


usage() {
    cat <<HELP

genstrap - gentoo base system bootstrap
based on debootstrap

usage: genstrap

Options:
    -h              display this help page
    -d              choose directory
    -a              choose architecture
    -s              choose sub-architecture
    -e              extra download options
                    avalible:
                        hardened+nomultilib
                        hardened-selinux+nomultilib
                        hardened-selinux
                        hardened
                        nomultilib
                        systemd
                        uclibc-hardened
                        uclibc-vanilla
    -g              create repo config gentoo.conf
    -r              create /etc/resolv.conf
    -l              use a downloaded stage tarball
    -u              only download a tarball

Defaults:
    directory   =   current directory
    arch        =   amd64
    sub-arch    =   amd64
    extras      =   none
    gentoo.conf =   no

Avalible arches and sub-arches:
    alpha
                    alpha
    amd64
                    amd64
                    x32
    arm
                    armv4tl
                    armv5tel
                    armv6j
                    armv6j_hardfp
                    armv7a
                    armv7a_hardfp
    hppa
                    hppa32
                    hppa64
                    hppa1.1
                    hppa2.0
    ia64
                    ia64
    ppc
                    ppc
                    ppc64
                    ppc64le
    s390
                    s390
                    s390x
    sh
                    sh4
                    sh4a
    sparc
                    sparc64
    x86
                    x86
                    i486
                    i686

HELP
}

bold_msg() {
    echo "$(tput bold)$1$(tput sgr0)"
}

err_msg() {
    echo "$(tput bold)$1$(tput sgr0)"
    exit 1
}

lookup_stage() {
    tarball_location=$(wget -q -O - "https://gentoo.osuosl.org/releases/$os_arch/autobuilds/latest-stage3-$os_subarch$os_extra.txt" | grep -E '^2' | grep -o '^\S*')
    # gives:
    # 20190821T214502Z/stage3-amd64-20190821T214502Z.tar.xz
    tarball_name=$(basename "$tarball_location")
    # gives:
    # stage3-amd64-20190821T214502Z.tar.xz
}

get_stage() {
    lookup_stage
    wget "https://gentoo.osuosl.org/releases/$os_arch/autobuilds/$tarball_location" -O $os_directory/$tarball_name
}

unpack_stage() {
    tar xpf $os_directory/stage3* -C $os_directory
}

repo_conf() {
    mkdir -p $os_directory/etc/portage/repos.conf
    cat > $os_directory/etc/portage/repos.conf/gentoo.conf <<GENTOO_CONF
[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo
sync-type = rsync
sync-uri = rsync://rsync.gentoo.org/gentoo-portage
auto-sync = yes
sync-rsync-verify-jobs = 1
sync-rsync-verify-metamanifest = yes
sync-rsync-verify-max-age = 24
sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc
sync-openpgp-key-refresh-retry-count = 40
sync-openpgp-key-refresh-retry-overall-timeout = 1200
sync-openpgp-key-refresh-retry-delay-exp-base = 2
sync-openpgp-key-refresh-retry-delay-max = 60
sync-openpgp-key-refresh-retry-delay-mult = 4
GENTOO_CONF
}

resolv_conf() {
    cat > $os_directory/etc/resolv.conf <<RESOLV_CONF
nameserver 1.1.1.1
nameserver 1.0.0.1
RESOLV_CONF
}


# Command line options

while [ -n "$1" ]; do
    case "$1" in
    -h | --help)
        usage
        exit 0
        ;;
    -d | --directory)
        os_directory="$2"
        ;;
    -a | --arch)
        os_arch="$2"
        ;;
    -s | --sub_arch)
        os_subarch="$2"
        ;;
    -e | --extra)
        os_extra="-$2"
        ;;
    -g | --repo_conf)
        do_gentoo_conf="yes"
        ;;
    -r | --resolv_conf)
        do_resolv_conf="yes"
        ;;
    -l | --no-download)
        do_download="no"
        ;;
    -u | --no-unpack)
        do_unpack="no"
        ;;
    -*)
        usage
        exit 1
        ;;
    esac
    shift
done


# Check root

(( EUID == 0 )) || (
    err_msg "This script must be run with root privileges!"
)


# Do some work

if [ $do_download = "yes" ]; then
    bold_msg "Downloading for $os_subarch$os_extra into $os_directory ..."
    get_stage
    bold_msg "Stage downloaded, OK"
fi

if [ $do_unpack = "yes" ]; then
    bold_msg "Unpacking stage tarball ..."
    unpack_stage
    bold_msg "Stage unpacked, OK"
fi

if [ $do_gentoo_conf = "yes" ]; then
    bold_msg "Writing gentoo.conf ..."
    repo_conf
    bold_msg "Written $os_directory/etc/portage/repos.conf/gentoo.conf , OK"
fi

if [ $do_resolv_conf = "yes" ]; then
    bold_msg "Writing resolv.conf ..."
    resolv_conf
    bold_msg "Written $os_directory/etc/resolv.conf , OK"
fi
